apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfa-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mfa-backend
  template:
    metadata:
      labels:
        app: mfa-backend
    spec:
      containers:
        - name: mfa-backend-container
          image: guruprasadsingirikonda/mfa:v2
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "512m"
              memory: "512Mi"
            requests:
              cpu: "256m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /mfa-service/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /mfa-service/health/readiness
            initialDelaySeconds: 5
            periodSeconds: 10
