apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfa-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mfa-backend
  template:
    metadata:
      labels:
        app: mfa-backend
    spec:
      containers:
        - name: mfa-backend-container
          image: guruprasadsingirikonda/mfa:v3
          ports:
            - containerPort: 9095
          resources:
            limits:
              cpu: "512m"
              memory: "512Mi"
            requests:
              cpu: "512m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /mfa-service/health/liveness
              port: 9095
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /mfa-service/health/readiness
              port: 9095
            initialDelaySeconds: 120
            periodSeconds: 10
