apiVersion: v1
kind: Service
metadata:
  name: mfa-backend-service
  namespace: default
spec:
  selector:
    app: mfa-backend
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9095
  type: ClusterIP
